# Generated by Django 4.1.5 on 2023-01-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogville', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='Blogville.profile'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
