# Generated by Django 4.1.5 on 2023-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogville', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media\\profile_pictures\\kindpng_4212275.png', null=True, upload_to='profile_pictures'),
        ),
    ]
