# Generated by Django 4.1.5 on 2023-02-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogville', '0019_blogpost_likes_delete_like_unlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
